version: '3.9'

services:
  db:
    image: postgres:17.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: wewe-rss
      TZ: 'America/Los_Angeles'
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      timeout: 45s
      interval: 10s
      retries: 10

  app:
    image: cooderl/wewe-rss:latest
    ports:
      - 54789:4000
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://postgres:123456@db:5432/wewe-rss
      - DATABASE_TYPE=postgres
      - AUTH_CODE=123567
      - FEED_MODE=fulltext
      - CRON_EXPRESSION=35 5,17 * * *
      - MAX_REQUEST_PER_MINUTE=60
      - SERVER_ORIGIN_URL=http://localhost:54789
      - NODE_ENV=production

networks:
  wewe-rss:

volumes:
  db_data: